/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import static org.junit.jupiter.api.Assertions.*;
import static org.example.revString.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        
        assertEquals(classUnderTest.getGreeting(), "Hello World!");
        
    }
    public static String[] inputs={"Value", "Hello", "World"};
    public static String[] expectedOutcome={"eulaV", "olleH", "dlroW"};

    @Test
    void testCase2(){
        for(int i=0; i<inputs.length; i++){
            assertEquals(rev(inputs[i]), expectedOutcome[i]);
        }
    }

    @ParameterizedTest
    @CsvSource({
        "Akash, hsakA",
        "Hello, olleH",
        "RACECAR, RaCECAR"
    })
    void testWithParameterizedTest(String input, String expected){
        assertEquals(expected, rev(input));
    }



    // @Test
    // void test(){
    //     System.out.println("hello");
    //     assertEquals(Math.pow(2, 5), 32);
        
    // }
}
